name: hashed
description: Hashed Wallet

version: 1.0.0+9

environment:
  sdk: '>=2.17.0 <3.0.0'

analyzer:
  enable-experiment: extension-methods

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  step_progress_indicator: ^1.0.2
  uni_links: ^0.5.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^5.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.1.0
  local_auth: ^2.1.2
  timeago: ^3.1.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  share: ^2.0.4
  carousel_slider: ^4.0.0
  qr_flutter: ^4.0.0
  image_picker: ^0.8.5+3
  qr_code_scanner: ^1.0.0
  collection: ^1.15.0
  mask_text_input_formatter: ^2.0.0
  lottie: ^1.2.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  palette_generator: ^0.3.2
  webview_flutter: ^3.0.0
  json_annotation: ^4.4.0
  bs58check: ^1.0.2
  pointycastle: ^3.4.0
  hdkey: ^0.0.1
  permission_handler: ^10.0.0
  json_schema2: ^2.0.2
  flutter_inappwebview: ^5.4.3+7
  google_fonts: ^3.0.1
  flutter_aes_ecb_pkcs5: ^0.1.2
  flutter_native_splash: ^2.2.6
  firebase_dynamic_links: ^5.0.11
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.9

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  #color: "#42a5f5"
  background_image: "assets/images/splash/hash-splash.png"

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  mockito: ^5.0.7
  lint: ^1.7.2
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "app_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/ecosystem.svg
    - assets/images/app_icon.png
    - assets/images/seeds_currency_icon.svg
    - assets/images/loading.png
    - assets/images/seeds_symbol_forest.png
    - assets/images/community.svg
    - assets/images/governance.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/ecosystem.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/logout.svg
    - assets/images/lotus_support_small.svg
    - assets/images/lotus_support_big.svg
    - assets/images/seeds.png
    - assets/images/seeds_light_wallet_logo.png
    - assets/images/guardians/guardian_tutorial_1.png
    - assets/images/guardians/guardian_tutorial_2.png
    - assets/images/guardians/guardian_tutorial_3.png
    - assets/images/guardians/guardian_tutorial_4.png
    - assets/images/guardians/invite_guardian_mail.svg
    - assets/images/guardians/check_circle.png
    - assets/images/guardians/invite_guardian_mail.png
    - assets/images/guardians/guardian_shield.png
    - assets/images/guardians/onboarding/onboarding_1.jpg
    - assets/images/guardians/onboarding/onboarding_2.jpg
    - assets/images/guardians/onboarding/onboarding_3.jpg
    - assets/images/guardians/onboarding/onboarding_4.jpg
    - assets/images/navigation_bar/wallet.svg
    - assets/images/navigation_bar/carbon_settings_selected.svg
    - assets/images/navigation_bar/carbon_settings_unselected.svg
    - assets/images/navigation_bar/user_profile.svg
    - assets/images/navigation_bar/wallet_selected.svg
    - assets/images/navigation_bar/user_profile_selected.svg
    - assets/images/wallet/arrow_up.svg
    - assets/images/wallet/share_transaction_id.svg
    - assets/images/wallet/leaves_bttm_left.png
    - assets/images/wallet/leaves_bttm_right.png
    - assets/images/wallet/arrow_down.svg
    - assets/images/appbar/hashed_logo.png
    - assets/images/wallet/app_bar/appbar_icon.svg
    - assets/images/wallet/app_bar/scan_qr_code_icon.svg
    - assets/images/wallet/app_bar/appbar_seeds_text.svg
    - assets/images/wallet/currency_info_cards/seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/husd/logo.jpg
    - assets/images/wallet/currency_info_cards/husd/background.jpg
    - assets/images/wallet/currency_info_cards/seeds/background.jpg
    - assets/images/wallet/currency_info_cards/lscl/background.jpg
    - assets/images/wallet/currency_info_cards/lscl/logo.png
    - assets/images/wallet/currency_info_cards/planted_seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/hypha/background.jpg
    - assets/images/wallet/currency_info_cards/hypha/logo.jpg
    - assets/images/wallet/currency_info_cards/stars/background.jpg
    - assets/images/wallet/currency_info_cards/stars/logo.jpg
    - assets/images/wallet/currency_info_cards/tlos/background.png
    - assets/images/wallet/currency_info_cards/hashed/background.png
    - assets/images/wallet/currency_info_cards/tlos/logo.png
    - assets/images/wallet/currency_info_cards/seeds/seeds_check_transp.png
    - assets/images/wallet/currency_info_cards/experimental.png
    - assets/images/security/key_guardians_icon.svg
    - assets/images/security/success_outlined_icon.svg
    - assets/images/citizenship/reputation.svg
    - assets/images/citizenship/community.svg
    - assets/images/citizenship/planted.svg
    - assets/images/citizenship/age.svg
    - assets/images/citizenship/transaction.svg
    - assets/images/contribution/reputation.svg
    - assets/images/contribution/community.svg
    - assets/images/contribution/planted.svg
    - assets/images/contribution/transaction.svg
    - assets/images/contribution/contribution_detail/petals_left.png
    - assets/images/contribution/contribution_detail/petals_right.png
    - assets/images/seeds_logo.svg
    - assets/images/login/wallet_logo.png
    - assets/images/receive/receive_input_seeds.svg
    - assets/images/receive/merchant.svg
    - assets/images/currency_switch_button.svg
    - assets/images/scan.svg
    - assets/images/clarity_network_setting.svg
    - assets/images/send/telos_logo.png
    - assets/images/transfer/seeds_icon.svg
    - assets/images/transfer/arrow_up.svg
    - assets/images/hashed_logo_black.png
    - assets/images/settings/logout_icon.svg
    - assets/animations/forest.json
    - assets/animations/send_animation.json
    - assets/images/google/powered_by_google_on_white.png
    - assets/images/google/powered_by_google_on_non_white.png
    - assets/google_fonts/SourceSansPro-Black.ttf
    - assets/google_fonts/SourceSansPro-BlackItalic.ttf
    - assets/google_fonts/SourceSansPro-Bold.ttf
    - assets/google_fonts/SourceSansPro-BoldItalic.ttf
    - assets/google_fonts/SourceSansPro-ExtraLight.ttf
    - assets/google_fonts/SourceSansPro-ExtraLightItalic.ttf
    - assets/google_fonts/SourceSansPro-Italic.ttf
    - assets/google_fonts/SourceSansPro-Light.ttf
    - assets/google_fonts/SourceSansPro-LightItalic.ttf
    - assets/google_fonts/SourceSansPro-Regular.ttf
    - assets/google_fonts/SourceSansPro-SemiBold.ttf
    - assets/google_fonts/SourceSansPro-SemiBoldItalic.ttf

    - assets/polkadot/sdk/lib/ssl/
    - assets/polkadot/sdk/assets/index.html
    - assets/polkadot/sdk/js_api/dist/main.js
    - assets/polkadot/sdk/js_as_extension/dist/main.js

    - assets/polkadot/default_endpoints.json
    - assets/polkadot/assets_info.txt
    - assets/polkadot/logo_info.json

    # assets end